MY_KERNEL_OUT := $(ANDROID_BUILD_TOP)/$(KERNEL_SRC)/out
#MY_MAKE := $(KERNEL_SRC)/../mymake TARGET_PRODUCT=tinnoes77_s9091 MTK_ROOT_CUSTOM=$(ANDROID_BUILD_TOP)/$(KERNEL_SRC)/../mediatek/custom KBUILD_OUTPUT_SUPPORT=yes -j8
MY_MAKE := $(MAKE) TARGET_PRODUCT=tinnoes77_s9091 MTK_ROOT_CUSTOM=$(ANDROID_BUILD_TOP)/$(KERNEL_SRC)/../mediatek/custom KBUILD_OUTPUT_SUPPORT=yes -j8

MY_ARM_CROSS_COMPILE := CROSS_COMPILE=$(ANDROID_BUILD_TOP)/prebuilt/linux-x86/toolchain/$(TARGET_KERNEL_CUSTOM_TOOLCHAIN)/bin/$(TARGET_KERNEL_CUSTOM_TOOLCHAIN_BIN)

$(MY_KERNEL_OUT):
	#We can't use the symlink because this breaks the build
	#test -d $(MY_KERNEL_OUT) || ln -s $(KERNEL_OUT) $(MY_KERNEL_OUT)
	test -d $(MY_KERNEL_OUT) || mkdir -p $(MY_KERNEL_OUT)

$(KERNEL_CONFIG): $(MY_KERNEL_OUT)
	cp -r $(KERNEL_SRC)/../output_files/* $(MY_KERNEL_OUT)/ 
	$(MY_MAKE) -C $(KERNEL_SRC) O=$(MY_KERNEL_OUT) ARCH=$(TARGET_ARCH) $(MY_ARM_CROSS_COMPILE) $(KERNEL_DEFCONFIG)

$(MY_KERNEL_OUT)/piggy : $(TARGET_PREBUILT_INT_KERNEL)
	$(hide) gunzip -c $(MY_KERNEL_OUT)/arch/$(TARGET_ARCH)/boot/compressed/piggy.gzip > $(MY_KERNEL_OUT)/piggy

TARGET_KERNEL_BINARIES: $(MY_KERNEL_OUT) $(KERNEL_CONFIG) $(KERNEL_HEADERS_INSTALL)
	$(MY_MAKE) -C $(KERNEL_SRC) O=$(MY_KERNEL_OUT) ARCH=$(TARGET_ARCH) $(MY_ARM_CROSS_COMPILE) $(TARGET_PREBUILT_INT_KERNEL_TYPE)
	$(MY_MAKE) -C $(KERNEL_SRC) O=$(MY_KERNEL_OUT) ARCH=$(TARGET_ARCH) $(MY_ARM_CROSS_COMPILE) modules
	$(MY_MAKE) -C $(KERNEL_SRC) O=$(MY_KERNEL_OUT) INSTALL_MOD_PATH=$(KERNEL_OUT)/../../$(KERNEL_MODULES_INSTALL) ARCH=$(TARGET_ARCH) $(MY_ARM_CROSS_COMPILE) modules_install
	cp -r $(MY_KERNEL_OUT)/* $(KERNEL_OUT)	
	$(mv-modules)
	$(clean-module-folder)

$(TARGET_KERNEL_MODULES): TARGET_KERNEL_BINARIES

$(TARGET_PREBUILT_INT_KERNEL): $(TARGET_KERNEL_MODULES)
	$(mv-modules)
	$(clean-module-folder)

$(KERNEL_HEADERS_INSTALL): $(MY_KERNEL_OUT) $(KERNEL_CONFIG)
	$(MY_MAKE) -C $(KERNEL_SRC) O=$(MY_KERNEL_OUT) ARCH=$(TARGET_ARCH) $(MY_ARM_CROSS_COMPILE) headers_install

